--- 
title: "Introduction to the Epistemic Network Analysis webtool"
author: "Authors"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is an introduction to the Epistemic Network Analysis web tool."
---

# Preface {-}

This is an introduction to the **Epistemic Network Analysis webtool** that can be accessed here: <https://www.epistemicnetwork.org>. 
Shakespeare dataset is used to demonstrate the ENA webtool and can be downloaded here: link.

## Motivation {-}

Our motivation ... 

## Structure of the book {-}

#### Chapter 1 What is ENA? {-}
ENA Workflow <br/>

#### Chapter 2 How to prepare data for ENA? {-}
Data Coding <br/>
Coding Validation <br/>
Data Formatting <br/>

#### Chapter 3 How is ENA developed? {-}

#### Chapter 4 ENA webtool: Basics {-}
Uploading the data <br/>
Tutorial mode <br/>
Plot operations <br/>
Set operations <br/>

#### Chapter 5 ENA webtool: Units {-}
Mean options <br/>
Hide/unhide <br/>
Exclude/include <br/>
Create Sample <br/>
Sphere Norm <br/>
Zero Points at Origin <br/>
Mean Rotation <br/>

#### Chapter 6 ENA webtool: Conversation {-}
Hide/unhide <br/>
Exclude/include <br/>
Moving Stanza <br/>
Whole Conversation <br/>
Infinite Stanza <br/>
Threaded Data <br/>

#### Chapter 7 ENA webtool: Codes {-}
Hide/unhide <br/>
Exclude/include <br/>
Highlight <br/>
Use rotation matrix <br/>
Code variables to display <br/>
Weighted model <br/>

#### Chapter 8 ENA webtool: Plot tools {-}
**_Dimensions_** <br/>
Dimension labels <br/>
Flip dimensions <br/>
Variance explained <br/>
Dimension types <br/>

**_Plotted points_** <br/>
Scale units <br/>
Unit labels <br/>
Group labels <br/>
Comparison <br/>
Text size <br/>

**_Network graph_** <br/>
Code labels <br/>
Show unconnected codes <br/>
Connection weights <br/>
Minimum edge weight <br/>
Scale for edge weigths <br/>
Weight group networks <br/>

#### Chapter 9 ENA webtool: Data view {-}
Exclude/include <br/>

#### Chapter 10 ENA webtool: Stats {-}
Comparison: parametric/non-parametric <br/>
Goodness of Fit & Variance <br/>
Theory Methods <br/>

#### Chapter 14 Examples of ENA models {-}
Short summary of the Shakespeare plays <br/>
Code elimination techniques <br/>
Model 1: Comparison (not means rotation) between Individuals <br/>
Model 2: Trajectory model by acts <br/>
Model 3: Means Rotation between Romeo & Juliet and Hamlet <br/>


## Acknowledgments {-}